name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GHC
        uses:  haskell-actions/setup@v2
        with:
          ghc-version: '9.4.8' 
          cabal-version: '3.10.3.0'
          enable-stack: true
          stack-version: '3.1.1'

      - name: Cache stack dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('stack.yaml') }}

      - name: Install dependencies
        run: stack setup && stack build --only-dependencies

      - name: Build project
        run: stack build

      - name: Run tests
        run: stack test
