name: Haskell CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        options: >-
          --health-cmd="pg_isready -U myuser -d mydb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    env:
      TEST_DATABASE_URL: postgres://myuser:mypassword@localhost:5432/mydb
    steps:
      
      - uses: actions/checkout@v4
      - uses: 1arp/create-a-file-action@0.4.5
        with:
          path: .
          file: .env
          content: "TEST_DATABASE_URL: postgres://myuser:mypassword@localhost:5432/mydb"
      - uses: actions/cache@v4
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}
      - run: ghcup list --tool ghc --hide-old
      - run: ghcup install ghc 9.6.6 --set
      - run: stack config set system-ghc true
      - run: stack config set install-ghc false
      - run: stack build --haddock --allow-newer
      - run: stack build --test --no-run-tests --allow-newer
      - run: stack test
