name: Haskell CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}
      - run: ghcup list --tool ghc --hide-old
      - run: ghcup install ghc 9.6.6 --set
      - run: stack config set system-ghc true
      - run: stack config set install-ghc false
      - run: stack build --haddock --allow-newer
      - run: stack build --test --no-run-tests --allow-newer
      - run: stack test
