name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read


jobs:
  testhaskell:
    name: Stack test
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4.8' 
          cabal-version: '3.10.3.0'
          enable-stack: true
          stack-version: '3.1.1'
      - name: "Build the project"
        run: "stack build"
      - name: "Run tests"
        run: "stack test"
